version: "3.8"

services:
  app:
    image: react-native
    build: ./Project
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - backend
    ports:
      - $EXPRESS_LOCAL_PORT:$EXPRESS_DOCKER_PORT
    networks:
      - mynetwork
  backend:
    image: express
    build: ./Project/server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - mynetwork

networks:
  mynetwork:

    